//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace suezCanalBank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public string userName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string userPassword { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "confirm Password")]
        [DataType(DataType.Password)]

        [Compare("userPassword", ErrorMessage = "password doesn’t match,please try again")]
        public string confirmPassword { get; set; }
    }
}
